name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
        cache: true

    - name: Test
      shell: sh
      run: go test -coverprofile=/tmp/code.coverage ./...

    - name: Upload coverage
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        go install github.com/mattn/goveralls@latest
        goveralls -coverprofile=/tmp/code.coverage -service=github

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
        cache: true

    - name: Build
      shell: sh
      run: scripts/build.sh build all

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: artifacts
        path: builds/*

  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.ref == 'refs/heads/master'
    needs: build
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: artifacts
        path: artifacts

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: latest
        name: latest
        make_latest: true
        files: artifacts/*
